spring:
  datasource:
    # 动态数据源
    dynamic:
      p6spy: true # 性能分析， 生产环境建议关闭
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://www.zyc.cool:22002/nuclear-boot-plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        #连接池名字
        pool-name: zerobug-boot-hikari-cp
        #最小空闲连接数量
        minimum-idle: 10
        #空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 60000
        #连接池最大连接数，默认是10
        maximum-pool-size: 10
        #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        #数据库连接超时时间,默认30秒，即30000
        connection-timeout: 30000
        # 配置检测连接是否有效
        connection-test-query: SELECT 1
  # redis 配置
  redis:
    # 地址
    host: www.zyc.cool
    # 端口，默认为6379
    port: 22004
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


zerobug:
  swagger:
    license:
    licenseUrl:
    termsOfServiceUrl:
    version: '@project.version@'
    global-operation-parameters:
      - name: Authorization
        in: header
        description: Bearer token
        required: true
        type: string
        default: Bearer
    groups:
      oauth:
        title: 认证模块
        base-package: cn.com.zerobug.module.impl.auth.controller
      system:
        title: 系统模块
        base-package: cn.com.zerobug.module.impl.system.controller
  filter:
    encrypt:
      enable: true
      crypto-type: SM4
      private-key: 8fd4d21cda34690b8294a07ba64e5c2a
    xss: # 不支持富文本
      # 开启xss 过滤
      enable: true
      # xss模式 INTERCEPT（默认） ESCAPE
      pattern: INTERCEPT
      # 包含路径 默认 /** ，多个路径请用 ','号分割
      include-paths: /**
      # 忽略路径，可以用@FilterIgnore 进行忽略 -> 新版本不需要带 servlet.context-path
      ignore-paths:
        - /xxxx/xxxx
    sql: # 不支持富文本
      # 开启sql 过滤
      enable: true
      # 包含路径 默认 /** ，多个路径请用 ','号分割
      include-paths: /**
      # 忽略路径，可以用@FilterIgnore 进行忽略 -> 新版本不需要带 servlet.context-path
      ignore-paths:
        - /xxxx/xxxx


knife4j:
  # 开启knife4j
  enable: true
  setting:
    # 开启重载缓存参数
    enableReloadCacheParameter: true
    # 开启版本支持
    enableVersion: true
    # 开启动态参数
    enableDynamicParameter: true
    # 页脚
    enableFooter: false
    # 页脚定制
    enableFooterCustom: true
    # 页脚自定义内容
    footerCustomContent: zerobug-boot v3.0.0 © 2021-2022